name: pubstream
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^8.0.0
  flexible_text: ^0.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  shared:
    path: ../shared
  shared_preferences: ^2.3.3
  supercharged: ^2.1.1
  talker_flutter: ^4.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/