name: pubstream
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^8.1.1
  flexible_text: ^1.1.0+3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  shared:
    path: ../shared
  shared_preferences: ^2.5.2
  supercharged: ^2.1.1
  talker_flutter: ^4.7.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  timeago: ^3.2.2
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.8.2
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/