name: server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^4.0.4
  collection: ^1.19.1
  dart_frog: ^1.1.0
  freezed_annotation: ^2.4.4
  googleapis: ^14.0.0
  http: ^1.2.2
  http_parser: ^4.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mime: ^2.0.0
  mongo_dart: ^0.10.4
  path: ^1.9.1
  pub_semver: ^2.1.4
  shared:
    path: ../shared
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0
