name: shared
description: This package contains files required by both frontend and backend for pubstream
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  lints: ^5.1.1
  test: ^1.24.0
  very_good_analysis: ^7.0.0
